version: '3.8'

services:
  apis:
    build :
      context : .
      args:
        NODE_ENV_ARG: ${NODE_ENV}
    image : ${IMAGE_NAME}
    container_name : ${CONTAINER_NAME}
    ports :
      - '${PORT}:${PORT}'
      # - '${ADMIN_PORT}:${ADMIN_PORT}'
    restart : always
    networks:
      - gp-network

networks:
  gp-network:
    name : gp-network
    