spring.application.name=cart
Spring.datasource.url=jdbc:mysql://localhost:3306/cart
Spring.datasource.username=root
Spring.datasource.password=janamourad
Spring.jpa.show-sql=false
Spring.jpa.generate-ddl=true
Spring.jpa.hibernate.ddl-auto=update
server.port=8080