spring:
  datasource:
    url: jdbc:mysql://db21560.public.databaseasp.net:3306/db21560?useSSL=true&requireSSL=false&verifyServerCertificate=false&zeroDateTimeBehavior=convertToNull
    username: db21560
    password: "f?9H6F@r-kA4"
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    database: mysql

server:
  port: 8055