spring:
  application:
    name: server
  datasource:
    url: jdbc:mysql://localhost:3300/nextronica
    username: hambolla
    password: hambollino
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    database: mysql

server:
  port: 8055